### ISSUE TITLE
rebuild for SDK 6.0+??

### ISSUE THREAD

**Issue by chrystoffer** [brownemint/Ti-Android-CameraView#17]
Any prediction to work on SDK 6.0+??
tks

**Comment by chrystoffer** [comment]
I tried this version but it shows this error
https://github.com/gimdongwoo/Ti-Android-CameraView/blob/4a9f2099da24bce8ce7e8b6ef2a5c863e9e865f8/dist/pw.custom.androidcamera-android-0.7.3.zip
SDK -> 6.0.1.GA

[ERROR] :  TiApplication: (main) [2325,2325] Sending event: exception on thread: main msg:java.lang.NullPointerException; Titanium 6.0.1,2016/12/19 16:51,undefined
[ERROR] :  TiApplication: java.lang.NullPointerException
[ERROR] :  TiApplication: 	at pw.custom.androidcamera.CameraViewProxy$CameraView.surfaceCreated(CameraViewProxy.java:130)
[ERROR] :  TiApplication: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
[ERROR] :  TiApplication: 	at android.view.SurfaceView.access$000(SurfaceView.java:96)
[ERROR] :  TiApplication: 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:185)
[ERROR] :  TiApplication: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1994)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
[ERROR] :  TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:544)
[ERROR] :  TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
[ERROR] :  TiApplication: 	at android.os.Handler.handleCallback(Handler.java:733)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5584)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)
[ERROR] :  D/gralloc.sc8830(  165): fb_post fps = 3.792300
[ERROR] :  E/android.os.Debug(  590): !@Dumpstate > sdumpstate -k -t -z -d -m 21911 -o /data/log/dumpstate_app_error
[ERROR] :  D/Launcher.HomeView(  949): onStart
[ERROR] :  D/Launcher.HomeView(  949): onResume
[ERROR] :  D/gralloc.sc8830(  165): fb_post fps = 34.600986
[ERROR] :  D/gralloc.sc8830(  165): fb_post fps = 7.873027
[ERROR] :  I/PowerManagerService-JNI(  590): CheckForString returning : -1
[ERROR] :  D/gralloc.sc8830(  165): fb_post fps = 0.994265

**Comment by brownemint** [comment]
I will be looking to update this for Ti SDK 6.0.x in the coming weeks, but right now it isn't a concern for me as I am still using Ti SDK 5.5.1 without issues. If you are having an issue with gimdongwoo's code I suggest you open an issue with him.

**Comment by brownemint** [comment]
The latest version uploaded works with Ti SDK 6.0.2.GA and was tested on Oneplus One running Android 6.0.1
