### ISSUE TITLE
blob picture

### ISSUE THREAD

**Issue by Moulay92** [brownemint/Ti-Android-CameraView#20]
Please, how can I upload picture in server, I dont know how to convert  it to blob just from path.
please i need answer.

**Comment by brownemint** [comment]
You have the path, so just open it as a file:
`var file = Ti.Filesystem.getFile(<path>);`

Then use the Network HTTPClient to upload it. This is all in the [Appcelerator Documentation](http://docs.appcelerator.com/platform/latest/#!/guide/File_Uploads_and_Downloads)
