### ISSUE TITLE
Camera freeze are taking picture

### ISSUE THREAD

**Issue by kosso** [brownemint/Ti-Android-CameraView#6]
Hi,

Thanks for this module. But should the camera image freeze after taking a photo? 
I'd like to be able to take a few, while keeping the camera 'live'. 

Testing on Moto G. Android 4.4.4  TiSDK 3.5.1.GA

Thanks!

**Comment by brownemint** [comment]
Hi Kosso,
The module was designed with one picture at a time in mind. I'll look into extending it with your suggestion in a future update.

**Comment by kosso** [comment]
Ah ok. I wasn't missing something then ;)

Being able to take more than one photo while still viewing through the camera would be very useful, thanks ;)   

eg: An app for creating short stop-frame-animations, where the previous image is "onion-skinned" over the view to position the next frame. etc. etc. 

Cheers!

**Comment by brownemint** [comment]
I just did a quick update there that should do what you suggested (0.6.1). You can use a new property called pictureTimeout to set how long the picture will "freeze" for before the preview is back "live". I've set the default at 1000ms (1 second).

**Comment by kosso** [comment]
Hi. 
That's great. Thanks. I'm give it a go.

btw, earlier I found a module which appears to be a modified version of your code, which also includes the ability to set the camera resolution : https://github.com/rpavez/ti-camera-pro/tree/master/src/com/ti/camera/pro
